/**
 * 公式助手符号库（WPS 公式助手风格的面板式分类数据）。
 *
 * - `latex` 为点击后插入源码的模板，占位符统一用 `\square`（KaTeX 合法、渲染为 □）；
 *   插入后编辑器自动选中第一个占位符，键入即替换。
 * - 所有条目均为 KaTeX 可渲染写法（写完后经 katex.renderToString 自检，勿引入 KaTeX 不支持的宏）。
 * - `label` 为按钮 tooltip，按钮本体渲染 `latex` 的 KaTeX 预览。
 */
export const PLACEHOLDER = '\\square'

export interface FormulaSymbolItem {
  /** 中文提示（按钮 title） */
  label: string
  /** 插入到 LaTeX 源码的片段，可含 PLACEHOLDER */
  latex: string
}

export interface FormulaSymbolCategory {
  key: string
  title: string
  items: FormulaSymbolItem[]
}

const P = PLACEHOLDER

export const FORMULA_CATEGORIES: FormulaSymbolCategory[] = [
  {
    key: 'base',
    title: '基础数学符号',
    items: [
      { label: '等号', latex: '=' },
      { label: '加号', latex: '+' },
      { label: '减号', latex: '-' },
      { label: '乘号', latex: '\\times' },
      { label: '除号', latex: '\\div' },
      { label: '点乘', latex: '\\cdot' },
      { label: '正负号', latex: '\\pm' },
      { label: '负正号', latex: '\\mp' },
      { label: '小于', latex: '\\lt' },
      { label: '大于', latex: '\\gt' },
      { label: '小于等于', latex: '\\leq' },
      { label: '大于等于', latex: '\\geq' },
      { label: '不等于', latex: '\\neq' },
      { label: '约等于', latex: '\\approx' },
      { label: '恒等于', latex: '\\equiv' },
      { label: '全等于', latex: '\\cong' },
      { label: '正比于', latex: '\\propto' },
      { label: '无穷大', latex: '\\infty' },
      { label: '相似于', latex: '\\sim' },
      { label: '整除（竖线）', latex: '\\mid' },
      { label: '所以', latex: '\\therefore' },
      { label: '因为', latex: '\\because' },
      { label: '居中对齐省略号', latex: '\\cdots' },
      { label: '基线省略号', latex: '\\ldots' },
      { label: '竖省略号', latex: '\\vdots' },
      { label: '斜省略号', latex: '\\ddots' },
      { label: '任意', latex: '\\forall' },
      { label: '存在', latex: '\\exists' },
      { label: '不存在', latex: '\\nexists' },
      { label: '复合圆点', latex: '\\circ' },
      { label: '度', latex: '^{\\circ}' },
    ],
  },
  {
    key: 'letters',
    title: '字母类符号',
    items: [
      { label: '花体小写 l', latex: '\\ell' },
      { label: '实部', latex: '\\Re' },
      { label: '虚部', latex: '\\Im' },
      { label: '阿列夫', latex: '\\aleph' },
      { label: '魏尔斯特拉斯 p', latex: '\\wp' },
      { label: '约化普朗克常数', latex: '\\hbar' },
      { label: '黑板粗体 k', latex: '\\Bbbk' },
      { label: '补集', latex: '\\complement' },
      { label: '翻转 F', latex: '\\Finv' },
      { label: '翻转 G', latex: '\\Game' },
      { label: '空集', latex: '\\emptyset' },
      { label: '空集（斜线）', latex: '\\varnothing' },
    ],
  },
  {
    key: 'operators',
    title: '运算符',
    items: [
      { label: '圆点', latex: '\\bullet' },
      { label: '五角星', latex: '\\star' },
      { label: '六角星', latex: '\\ast' },
      { label: '环加', latex: '\\oplus' },
      { label: '环减', latex: '\\ominus' },
      { label: '环乘', latex: '\\otimes' },
      { label: '环除', latex: '\\oslash' },
      { label: '环点', latex: '\\odot' },
      { label: '交集', latex: '\\cap' },
      { label: '并集', latex: '\\cup' },
      { label: '逻辑或', latex: '\\vee' },
      { label: '逻辑与', latex: '\\wedge' },
      { label: '先于', latex: '\\prec' },
      { label: '后于', latex: '\\succ' },
      { label: '先于等于', latex: '\\preceq' },
      { label: '后于等于', latex: '\\succeq' },
      { label: '集合差', latex: '\\setminus' },
      { label: '复合（函数）', latex: '\\circ' },
    ],
  },
  {
    key: 'arrows',
    title: '箭头',
    items: [
      { label: '向右箭头', latex: '\\rightarrow' },
      { label: '向左箭头', latex: '\\leftarrow' },
      { label: '左右双向箭头', latex: '\\leftrightarrow' },
      { label: '向右推导', latex: '\\Rightarrow' },
      { label: '向左推导', latex: '\\Leftarrow' },
      { label: '等价推导', latex: '\\Leftrightarrow' },
      { label: '映射', latex: '\\mapsto' },
      { label: '长右箭头', latex: '\\longrightarrow' },
      { label: '长左箭头', latex: '\\longleftarrow' },
      { label: '长双向箭头', latex: '\\longleftrightarrow' },
      { label: '上箭头', latex: '\\uparrow' },
      { label: '下箭头', latex: '\\downarrow' },
      { label: '上下箭头', latex: '\\updownarrow' },
      { label: '东北箭头', latex: '\\nearrow' },
      { label: '东南箭头', latex: '\\searrow' },
      { label: '西南箭头', latex: '\\swarrow' },
      { label: '西北箭头', latex: '\\nwarrow' },
      { label: '上方可带文字的长箭头', latex: `\\xrightarrow{${P}}` },
      { label: '下方可带文字的长箭头', latex: `\\xleftarrow{${P}}` },
    ],
  },
  {
    key: 'greek',
    title: '希腊字母',
    items: [
      { label: 'alpha', latex: '\\alpha' },
      { label: 'beta', latex: '\\beta' },
      { label: 'gamma', latex: '\\gamma' },
      { label: 'delta', latex: '\\delta' },
      { label: 'epsilon', latex: '\\epsilon' },
      { label: 'epsilon（变体）', latex: '\\varepsilon' },
      { label: 'zeta', latex: '\\zeta' },
      { label: 'eta', latex: '\\eta' },
      { label: 'theta', latex: '\\theta' },
      { label: 'theta（变体）', latex: '\\vartheta' },
      { label: 'iota', latex: '\\iota' },
      { label: 'kappa', latex: '\\kappa' },
      { label: 'lambda', latex: '\\lambda' },
      { label: 'mu', latex: '\\mu' },
      { label: 'nu', latex: '\\nu' },
      { label: 'xi', latex: '\\xi' },
      { label: 'pi', latex: '\\pi' },
      { label: 'rho', latex: '\\rho' },
      { label: 'rho（变体）', latex: '\\varrho' },
      { label: 'sigma', latex: '\\sigma' },
      { label: 'tau', latex: '\\tau' },
      { label: 'upsilon', latex: '\\upsilon' },
      { label: 'phi', latex: '\\phi' },
      { label: 'phi（变体）', latex: '\\varphi' },
      { label: 'chi', latex: '\\chi' },
      { label: 'psi', latex: '\\psi' },
      { label: 'omega', latex: '\\omega' },
      { label: 'Gamma', latex: '\\Gamma' },
      { label: 'Delta', latex: '\\Delta' },
      { label: 'Theta', latex: '\\Theta' },
      { label: 'Lambda', latex: '\\Lambda' },
      { label: 'Xi', latex: '\\Xi' },
      { label: 'Pi', latex: '\\Pi' },
      { label: 'Sigma', latex: '\\Sigma' },
      { label: 'Upsilon', latex: '\\Upsilon' },
      { label: 'Phi', latex: '\\Phi' },
      { label: 'Psi', latex: '\\Psi' },
      { label: 'Omega', latex: '\\Omega' },
    ],
  },
  {
    key: 'negated',
    title: '求反运算符',
    items: [
      { label: '不等于', latex: '\\neq' },
      { label: '不小于', latex: '\\nless' },
      { label: '不大于', latex: '\\ngtr' },
      { label: '不小于等于', latex: '\\nleq' },
      { label: '不大于等于', latex: '\\ngeq' },
      { label: '不恒等于', latex: '\\not\\equiv' },
      { label: '不相似', latex: '\\nsim' },
      { label: '不全等', latex: '\\ncong' },
      { label: '不属于', latex: '\\notin' },
      { label: '不是子集', latex: '\\nsubseteq' },
      { label: '不是超集', latex: '\\nsupseteq' },
      { label: '不整除', latex: '\\nmid' },
      { label: '不平行', latex: '\\nparallel' },
      { label: '不能推出', latex: '\\nrightarrow' },
      { label: '不能反推', latex: '\\nLeftarrow' },
      { label: '不等价', latex: '\\nLeftrightarrow' },
    ],
  },
  {
    key: 'script',
    title: '手写体',
    items: [
      { label: '花体模板（如 ℛ）', latex: `\\mathcal{${P}}` },
      { label: '德文尖角体模板（如 𝔤）', latex: `\\mathfrak{${P}}` },
      { label: '黑板粗体模板（如 ℝ）', latex: `\\mathbb{${P}}` },
      { label: '书写字体模板（如 𝒮）', latex: `\\mathscr{${P}}` },
      { label: '实数集 ℝ', latex: '\\mathbb{R}' },
      { label: '整数集 ℤ', latex: '\\mathbb{Z}' },
      { label: '自然数集 ℕ', latex: '\\mathbb{N}' },
      { label: '有理数集 ℚ', latex: '\\mathbb{Q}' },
      { label: '复数集 ℂ', latex: '\\mathbb{C}' },
      { label: '概率 ℙ', latex: '\\mathbb{P}' },
    ],
  },
  {
    key: 'geometry',
    title: '几何学',
    items: [
      { label: '角', latex: '\\angle' },
      { label: '角的度量', latex: '\\measuredangle' },
      { label: '三角形', latex: '\\triangle' },
      { label: '全等', latex: '\\cong' },
      { label: '平行', latex: '\\parallel' },
      { label: '不平行', latex: '\\nparallel' },
      { label: '垂直', latex: '\\perp' },
      { label: '正方形', latex: '\\square' },
      { label: '圆', latex: '\\bigcirc' },
      { label: '圆心点（⊙O）', latex: '\\odot' },
      { label: '弧 AB', latex: `\\overset{\\frown}{${P} B}` },
      { label: '度', latex: '^{\\circ}' },
      { label: '所以', latex: '\\therefore' },
      { label: '因为', latex: '\\because' },
      { label: '相似', latex: '\\sim' },
    ],
  },
  {
    key: 'fraction',
    title: '分数',
    items: [
      { label: '分数模板', latex: `\\frac{${P}}{${P}}` },
      { label: 'display 分数模板', latex: `\\dfrac{${P}}{${P}}` },
      { label: 'text 分数模板', latex: `\\tfrac{${P}}{${P}}` },
      { label: '连分数模板', latex: `\\cfrac{${P}}{${P}}` },
      { label: '常用分数：二分之一', latex: '\\frac{1}{2}' },
      { label: '常用分数：四分之一', latex: '\\frac{1}{4}' },
      { label: '常用分数：四分之三', latex: '\\frac{3}{4}' },
      { label: '分式示例', latex: '\\frac{x+1}{x-1}' },
    ],
  },
  {
    key: 'supsub',
    title: '上下标',
    items: [
      { label: '上标模板', latex: `x^{${P}}` },
      { label: '下标模板', latex: `x_{${P}}` },
      { label: '上下标模板', latex: `x_{${P}}^{${P}}` },
      { label: '平方', latex: 'x^{2}' },
      { label: '立方', latex: 'x^{3}' },
      { label: '下标 i', latex: 'x_{i}' },
      { label: '指数 e 的幂', latex: `e^{${P}}` },
      { label: '底数可换的对数下标', latex: `\\log_{${P}}` },
    ],
  },
  {
    key: 'integral',
    title: '积分',
    items: [
      { label: '不定积分号', latex: '\\int' },
      { label: '二重积分号', latex: '\\iint' },
      { label: '三重积分号', latex: '\\iiint' },
      { label: '曲线积分号', latex: '\\oint' },
      { label: '定积分模板', latex: `\\int_{${P}}^{${P}}` },
      { label: '定积分示例（牛顿-莱布尼茨）', latex: '\\int_{a}^{b} f(x)\\,dx' },
      { label: '二重积分示例', latex: '\\iint_{D} f(x,y)\\,d\\sigma' },
      { label: '闭合曲线积分示例', latex: '\\oint_{L} f(z)\\,dz' },
    ],
  },
  {
    key: 'radical',
    title: '根式',
    items: [
      { label: '平方根模板', latex: `\\sqrt{${P}}` },
      { label: 'n 次根式模板', latex: `\\sqrt[${P}]{${P}}` },
      { label: '根号内分数', latex: `\\sqrt{\\frac{${P}}{${P}}}` },
      { label: '根式在分母', latex: `\\frac{1}{\\sqrt{${P}}}` },
      { label: '常用根号 2', latex: '\\sqrt{2}' },
      { label: '常用根号（勾股）', latex: '\\sqrt{x^2+y^2}' },
    ],
  },
  {
    key: 'bigops',
    title: '大型运算符',
    items: [
      { label: '求和号', latex: '\\sum' },
      { label: '求积号', latex: '\\prod' },
      { label: '余积号', latex: '\\coprod' },
      { label: '并集大号', latex: '\\bigcup' },
      { label: '交集大号', latex: '\\bigcap' },
      { label: '环加大号', latex: '\\bigoplus' },
      { label: '环乘大号', latex: '\\bigotimes' },
      { label: '方形并', latex: '\\bigsqcup' },
      { label: '析取大号', latex: '\\bigvee' },
      { label: '合取大号', latex: '\\bigwedge' },
      { label: '连加（i 从 1 到 n）', latex: '\\sum_{i=1}^{n}' },
      { label: '连乘（i 从 1 到 n）', latex: '\\prod_{i=1}^{n}' },
      { label: '并集（i 从 1 到 n）', latex: '\\bigcup_{i=1}^{n}' },
      { label: '交集（i 从 1 到 n）', latex: '\\bigcap_{i=1}^{n}' },
    ],
  },
  {
    key: 'brackets',
    title: '括号',
    items: [
      { label: '圆括号（随内容伸缩）', latex: `\\left( ${P} \\right)` },
      { label: '方括号（随内容伸缩）', latex: `\\left[ ${P} \\right]` },
      { label: '花括号（随内容伸缩）', latex: `\\left\\{ ${P} \\right\\}` },
      { label: '上取整', latex: `\\lceil ${P} \\rceil` },
      { label: '下取整', latex: `\\lfloor ${P} \\rfloor` },
      { label: '内积尖括号', latex: `\\langle ${P} \\rangle` },
      { label: '绝对值', latex: `\\left\\vert ${P} \\right\\vert` },
      { label: '范数（双竖线）', latex: `\\left\\Vert ${P} \\right\\Vert` },
      { label: '分段函数（cases）', latex: `\\begin{cases} ${P} \\\\ ${P} \\end{cases}` },
    ],
  },
  {
    key: 'functions',
    title: '函数',
    items: [
      { label: '正弦', latex: '\\sin' },
      { label: '余弦', latex: '\\cos' },
      { label: '正切', latex: '\\tan' },
      { label: '余切', latex: '\\cot' },
      { label: '正割', latex: '\\sec' },
      { label: '余割', latex: '\\csc' },
      { label: '反正弦', latex: '\\arcsin' },
      { label: '反余弦', latex: '\\arccos' },
      { label: '反正切', latex: '\\arctan' },
      { label: '双曲正弦', latex: '\\sinh' },
      { label: '双曲余弦', latex: '\\cosh' },
      { label: '双曲正切', latex: '\\tanh' },
      { label: '最大值', latex: '\\max' },
      { label: '最小值', latex: '\\min' },
      { label: '指数函数', latex: '\\exp' },
    ],
  },
  {
    key: 'derivatives',
    title: '导数符号',
    items: [
      { label: '一阶导数 dy/dx', latex: '\\frac{dy}{dx}' },
      { label: '二阶导数', latex: '\\frac{d^{2}y}{dx^{2}}' },
      { label: "拉格朗日记法 y'", latex: "y'" },
      { label: '二阶（撇记）', latex: "y''" },
      { label: '牛顿点记一阶', latex: '\\dot{y}' },
      { label: '牛顿点记二阶', latex: '\\ddot{y}' },
      { label: '偏导模板', latex: '\\frac{\\partial}{\\partial x}' },
      { label: '二阶偏导模板', latex: '\\frac{\\partial^{2}}{\\partial x^{2}}' },
      { label: '偏微分号', latex: '\\partial' },
      { label: '梯度（nabla）', latex: '\\nabla' },
      { label: '梯度作用于 f', latex: '\\nabla f' },
      { label: '增量 Δy', latex: '\\Delta y' },
    ],
  },
  {
    key: 'limits',
    title: '极限和对数',
    items: [
      { label: '极限号', latex: '\\lim' },
      { label: '极限（x 趋于占位）', latex: `\\lim_{x \\to ${P}}` },
      { label: '极限（x 趋于无穷）', latex: '\\lim_{x \\to \\infty}' },
      { label: '极限（n 趋于无穷）', latex: '\\lim_{n \\to \\infty}' },
      { label: '下极限', latex: '\\liminf' },
      { label: '上极限', latex: '\\limsup' },
      { label: '对数（log）', latex: '\\log' },
      { label: '换底对数模板', latex: `\\log_{${P}} ${P}` },
      { label: '自然对数', latex: '\\ln' },
      { label: '常用对数（10 为底）', latex: '\\lg' },
    ],
  },
  {
    key: 'matrix',
    title: '矩阵',
    items: [
      { label: '圆括号矩阵 2×2', latex: `\\begin{pmatrix} ${P} & ${P} \\\\ ${P} & ${P} \\end{pmatrix}` },
      { label: '方括号矩阵 2×2', latex: `\\begin{bmatrix} ${P} & ${P} \\\\ ${P} & ${P} \\end{bmatrix}` },
      { label: '花括号矩阵 2×2', latex: `\\begin{Bmatrix} ${P} & ${P} \\\\ ${P} & ${P} \\end{Bmatrix}` },
      { label: '行列式 2×2', latex: `\\begin{vmatrix} ${P} & ${P} \\\\ ${P} & ${P} \\end{vmatrix}` },
      { label: '范数矩阵 2×2', latex: `\\begin{Vmatrix} ${P} & ${P} \\\\ ${P} & ${P} \\end{Vmatrix}` },
      { label: '圆括号矩阵 3×3', latex: `\\begin{pmatrix} ${P} & ${P} & ${P} \\\\ ${P} & ${P} & ${P} \\\\ ${P} & ${P} & ${P} \\end{pmatrix}` },
      { label: '方括号矩阵 3×3', latex: `\\begin{bmatrix} ${P} & ${P} & ${P} \\\\ ${P} & ${P} & ${P} \\\\ ${P} & ${P} & ${P} \\end{bmatrix}` },
      { label: '列向量（2 行）', latex: `\\begin{pmatrix} ${P} \\\\ ${P} \\end{pmatrix}` },
    ],
  },
]
