/**
 * 公式助手符号库（WPS 公式助手风格的面板式分类数据）。
 *
 * - `latex` 为点击后插入源码的模板，占位符统一用 `\square`（KaTeX 合法、渲染为 □）；
 *   插入后编辑器自动选中第一个占位符，键入即替换。
 * - `preview` 为可选的按钮预览源码，缺省用 `latex`。模板条目必须给 preview：
 *   否则按钮上只剩一排 □，用户看到的是「空白方块」而不是符号，这正是「有些符号显示不出来」的由来。
 * - 化学分类用 mhchem 的 `\ce{}`（由 packages/shared/src/utils/katex.ts 全局注册），
 *   物理/生物分类复用同一套 `\ce{}` + 常规数学写法。
 * - 所有条目均为 KaTeX 可渲染写法：写完经 `throwOnError: true` 自检 + 字体字形覆盖自检，
 *   勿引入 KaTeX 不支持的宏（0.18 起不支持的命令会渲染成红字而非抛错，肉眼极难发现）。
 * - `label` 为按钮 tooltip，按钮本体渲染 `preview ?? latex` 的 KaTeX 预览。
 */
export const PLACEHOLDER = '\\square'

export interface FormulaSymbolItem {
  /** 中文提示（按钮 title） */
  label: string
  /** 插入到 LaTeX 源码的片段，可含 PLACEHOLDER */
  latex: string
  /** 按钮上的预览源码；模板类条目用它渲染「填好样子的示例」，缺省等于 latex */
  preview?: string
}

export interface FormulaSymbolCategory {
  key: string
  title: string
  items: FormulaSymbolItem[]
}

const P = PLACEHOLDER

export const FORMULA_CATEGORIES: FormulaSymbolCategory[] = [
  {
    key: 'base',
    title: '基础数学符号',
    items: [
      { label: '等号', latex: '=' },
      { label: '加号', latex: '+' },
      { label: '减号', latex: '-' },
      { label: '乘号', latex: '\\times' },
      { label: '除号', latex: '\\div' },
      { label: '点乘', latex: '\\cdot' },
      { label: '正负号', latex: '\\pm' },
      { label: '负正号', latex: '\\mp' },
      { label: '小于', latex: '\\lt' },
      { label: '大于', latex: '\\gt' },
      { label: '小于等于', latex: '\\leq' },
      { label: '大于等于', latex: '\\geq' },
      { label: '不等于', latex: '\\neq' },
      { label: '约等于', latex: '\\approx' },
      { label: '恒等于', latex: '\\equiv' },
      { label: '全等于', latex: '\\cong' },
      { label: '正比于', latex: '\\propto' },
      { label: '无穷大', latex: '\\infty' },
      { label: '相似于', latex: '\\sim' },
      { label: '整除（竖线）', latex: '\\mid' },
      { label: '所以', latex: '\\therefore' },
      { label: '因为', latex: '\\because' },
      { label: '居中对齐省略号', latex: '\\cdots' },
      { label: '基线省略号', latex: '\\ldots' },
      { label: '竖省略号', latex: '\\vdots' },
      { label: '斜省略号', latex: '\\ddots' },
      { label: '任意', latex: '\\forall' },
      { label: '存在', latex: '\\exists' },
      { label: '不存在', latex: '\\nexists' },
      { label: '复合圆点', latex: '\\circ' },
      { label: '度', latex: '^{\\circ}' },
      { label: '百分号', latex: '\\%' },
      { label: '星号', latex: '\\ast' },
      { label: '实心圆点', latex: '\\bullet' },
      { label: '五角星', latex: '\\star' },
      { label: '冒号等于（定义）', latex: '\\mathrel{:=}' },
      { label: '冒号（比）', latex: ':' },
      { label: '竖线（条件、绝对值）', latex: '\\mid' },
      { label: '波浪号（约）', latex: '\\sim' },
    ],
  },
  {
    key: 'sets',
    title: '集合',
    items: [
      { label: '属于', latex: '\\in' },
      { label: '不属于', latex: '\\notin' },
      { label: '包含（反向属于）', latex: '\\ni' },
      { label: '子集', latex: '\\subset' },
      { label: '真子集', latex: '\\subsetneq' },
      { label: '不是子集', latex: '\\nsubseteq' },
      { label: '包含于等于', latex: '\\subseteq' },
      { label: '超集', latex: '\\supset' },
      { label: '真超集', latex: '\\supsetneq' },
      { label: '不是超集', latex: '\\nsupseteq' },
      { label: '包含等于', latex: '\\supseteq' },
      { label: '并集', latex: '\\cup' },
      { label: '交集', latex: '\\cap' },
      { label: '差集', latex: '\\setminus' },
      { label: '差集（细）', latex: '\\smallsetminus' },
      { label: '补集', latex: '\\complement' },
      { label: '补集（含全集 U）', latex: `\\complement_{\\mathrm{U}}${P}`, preview: '\\complement_{\\mathrm{U}}A' },
      { label: '空集', latex: '\\emptyset' },
      { label: '空集（斜线）', latex: '\\varnothing' },
      { label: '左侧方形子集', latex: '\\sqsubset' },
      { label: '左侧方形超集', latex: '\\sqsupset' },
      { label: '左侧方形包含', latex: '\\sqsubseteq' },
      { label: '左侧方形包含于', latex: '\\sqsupseteq' },
      { label: '元素个数（基数）', latex: `\\left\\vert ${P} \\right\\vert`, preview: '\\left\\vert A \\right\\vert' },
      { label: '幂集', latex: `\\mathcal{P}(${P})`, preview: '\\mathcal{P}(A)' },
      { label: '集合（条件表示）', latex: `\\left\\{ ${P} \\mid ${P} \\right\\}`, preview: '\\left\\{ x \\mid x \\gt 0 \\right\\}' },
      { label: '实数集 ℝ', latex: '\\mathbb{R}' },
      { label: '有理数集 ℚ', latex: '\\mathbb{Q}' },
      { label: '整数集 ℤ', latex: '\\mathbb{Z}' },
      { label: '自然数集 ℕ', latex: '\\mathbb{N}' },
      { label: '正整数集 ℕ*', latex: '\\mathbb{N}^{*}' },
      { label: '复数集 ℂ', latex: '\\mathbb{C}' },
    ],
  },
  {
    key: 'logic',
    title: '逻辑与推理',
    items: [
      { label: '非', latex: '\\neg' },
      { label: '且（逻辑与）', latex: '\\land' },
      { label: '或（逻辑或）', latex: '\\lor' },
      { label: '且（尖角）', latex: '\\wedge' },
      { label: '或（尖角）', latex: '\\vee' },
      { label: '蕴含（右推导）', latex: '\\Rightarrow' },
      { label: '蕴含（左推导）', latex: '\\Leftarrow' },
      { label: '等价', latex: '\\Leftrightarrow' },
      { label: '推出', latex: '\\implies' },
      { label: '被推出', latex: '\\impliedby' },
      { label: '当且仅当', latex: '\\iff' },
      { label: '真', latex: '\\top' },
      { label: '假', latex: '\\bot' },
      { label: '可推出', latex: '\\vdash' },
      { label: '不可推出', latex: '\\nvdash' },
      { label: '反向可推出', latex: '\\dashv' },
      { label: '满足', latex: '\\models' },
      { label: '满足（双线）', latex: '\\vDash' },
      { label: '强满足', latex: '\\Vdash' },
      { label: '不满足（双线）', latex: '\\nvDash' },
      { label: '证毕', latex: '\\blacksquare' },
      { label: '任意', latex: '\\forall' },
      { label: '存在', latex: '\\exists' },
      { label: '不存在', latex: '\\nexists' },
      { label: '所以', latex: '\\therefore' },
      { label: '因为', latex: '\\because' },
    ],
  },
  {
    key: 'relations',
    title: '关系与比较',
    items: [
      { label: '小于等于（倾斜）', latex: '\\leqslant' },
      { label: '大于等于（倾斜）', latex: '\\geqslant' },
      { label: '远小于', latex: '\\ll' },
      { label: '远大于', latex: '\\gg' },
      { label: '极小（三个小于）', latex: '\\lll' },
      { label: '极大（三个大于）', latex: '\\ggg' },
      { label: '渐进等于', latex: '\\simeq' },
      { label: '约等于（双波浪）', latex: '\\approxeq' },
      { label: '同阶', latex: '\\asymp' },
      { label: '定义为', latex: '\\triangleq' },
      { label: '点等于', latex: '\\doteq' },
      { label: '点等于（双点）', latex: '\\doteqdot' },
      { label: '环等于', latex: '\\circeq' },
      { label: '环圈等于', latex: '\\eqcirc' },
      { label: '上升点等于', latex: '\\risingdotseq' },
      { label: '下降点等于', latex: '\\fallingdotseq' },
      { label: '驼峰等于', latex: '\\bumpeq' },
      { label: '驼峰等于（粗）', latex: '\\Bumpeq' },
      { label: '近似小于', latex: '\\lesssim' },
      { label: '近似大于', latex: '\\gtrsim' },
      { label: '近似小于等于', latex: '\\lessapprox' },
      { label: '近似大于等于', latex: '\\gtrapprox' },
      { label: '小于或大于', latex: '\\lessgtr' },
      { label: '大于或小于', latex: '\\gtrless' },
      { label: '小于等于或大于', latex: '\\lesseqgtr' },
      { label: '大于等于或小于', latex: '\\gtreqless' },
      { label: '先于', latex: '\\prec' },
      { label: '后于', latex: '\\succ' },
      { label: '先于等于', latex: '\\preceq' },
      { label: '后于等于', latex: '\\succeq' },
      { label: '先于相似', latex: '\\precsim' },
      { label: '后于相似', latex: '\\succsim' },
      { label: '不先于', latex: '\\nprec' },
      { label: '不后于', latex: '\\nsucc' },
      { label: '整除', latex: '\\mid' },
      { label: '平行', latex: '\\parallel' },
      { label: '垂直', latex: '\\perp' },
      { label: '正比于', latex: '\\propto' },
      { label: '双冒号（比例）', latex: '::' },
    ],
  },
  {
    key: 'letters',
    title: '字母类符号',
    items: [
      { label: '花体小写 l', latex: '\\ell' },
      { label: '实部', latex: '\\Re' },
      { label: '虚部', latex: '\\Im' },
      { label: '阿列夫', latex: '\\aleph' },
      { label: '魏尔斯特拉斯 p', latex: '\\wp' },
      { label: '约化普朗克常数', latex: '\\hbar' },
      { label: '黑板粗体 k', latex: '\\Bbbk' },
      { label: '补集', latex: '\\complement' },
      { label: '翻转 F', latex: '\\Finv' },
      { label: '翻转 G', latex: '\\Game' },
      { label: '空集', latex: '\\emptyset' },
      { label: '空集（斜线）', latex: '\\varnothing' },
      { label: '自然常数 e', latex: '\\mathrm{e}' },
      { label: '虚数单位 i', latex: '\\mathrm{i}' },
      { label: '微分算子 d', latex: '\\mathrm{d}' },
      { label: '纳米符号', latex: '\\mathrm{nm}' },
      { label: '偏微分符号', latex: '\\partial' },
      { label: '梯度算子', latex: '\\nabla' },
    ],
  },
  {
    key: 'greek',
    title: '希腊字母',
    items: [
      { label: 'alpha', latex: '\\alpha' },
      { label: 'beta', latex: '\\beta' },
      { label: 'gamma', latex: '\\gamma' },
      { label: 'delta', latex: '\\delta' },
      { label: 'epsilon', latex: '\\epsilon' },
      { label: 'epsilon（变体）', latex: '\\varepsilon' },
      { label: 'zeta', latex: '\\zeta' },
      { label: 'eta', latex: '\\eta' },
      { label: 'theta', latex: '\\theta' },
      { label: 'theta（变体）', latex: '\\vartheta' },
      { label: 'iota', latex: '\\iota' },
      { label: 'kappa', latex: '\\kappa' },
      { label: 'kappa（变体）', latex: '\\varkappa' },
      { label: 'lambda', latex: '\\lambda' },
      { label: 'mu', latex: '\\mu' },
      { label: 'nu', latex: '\\nu' },
      { label: 'xi', latex: '\\xi' },
      { label: 'pi', latex: '\\pi' },
      { label: 'pi（变体）', latex: '\\varpi' },
      { label: 'rho', latex: '\\rho' },
      { label: 'rho（变体）', latex: '\\varrho' },
      { label: 'sigma', latex: '\\sigma' },
      { label: 'sigma（变体）', latex: '\\varsigma' },
      { label: 'tau', latex: '\\tau' },
      { label: 'upsilon', latex: '\\upsilon' },
      { label: 'phi', latex: '\\phi' },
      { label: 'phi（变体）', latex: '\\varphi' },
      { label: 'chi', latex: '\\chi' },
      { label: 'psi', latex: '\\psi' },
      { label: 'omega', latex: '\\omega' },
      { label: 'digamma', latex: '\\digamma' },
      { label: 'Gamma', latex: '\\Gamma' },
      { label: 'Delta', latex: '\\Delta' },
      { label: 'Theta', latex: '\\Theta' },
      { label: 'Theta（变体）', latex: '\\varTheta' },
      { label: 'Lambda', latex: '\\Lambda' },
      { label: 'Xi', latex: '\\Xi' },
      { label: 'Xi（变体）', latex: '\\varXi' },
      { label: 'Pi', latex: '\\Pi' },
      { label: 'Pi（变体）', latex: '\\varPi' },
      { label: 'Sigma', latex: '\\Sigma' },
      { label: 'Sigma（变体）', latex: '\\varSigma' },
      { label: 'Upsilon', latex: '\\Upsilon' },
      { label: 'Phi', latex: '\\Phi' },
      { label: 'Psi', latex: '\\Psi' },
      { label: 'Omega', latex: '\\Omega' },
    ],
  },
  {
    key: 'operators',
    title: '运算符',
    items: [
      { label: '圆点', latex: '\\bullet' },
      { label: '五角星', latex: '\\star' },
      { label: '六角星', latex: '\\ast' },
      { label: '菱形', latex: '\\diamond' },
      { label: '叉积', latex: '\\wr' },
      { label: '合并（余积）', latex: '\\amalg' },
      { label: '多重集并', latex: '\\uplus' },
      { label: '方形并', latex: '\\sqcup' },
      { label: '方形交', latex: '\\sqcap' },
      { label: '剑号', latex: '\\dagger' },
      { label: '双剑号', latex: '\\ddagger' },
      { label: '环加', latex: '\\oplus' },
      { label: '环减', latex: '\\ominus' },
      { label: '环乘', latex: '\\otimes' },
      { label: '环除', latex: '\\oslash' },
      { label: '环点', latex: '\\odot' },
      { label: '环星', latex: '\\circledast' },
      { label: '环圈', latex: '\\circledcirc' },
      { label: '环短横', latex: '\\circleddash' },
      { label: '方框加', latex: '\\boxplus' },
      { label: '方框减', latex: '\\boxminus' },
      { label: '方框乘', latex: '\\boxtimes' },
      { label: '方框点', latex: '\\boxdot' },
      { label: '交集', latex: '\\cap' },
      { label: '并集', latex: '\\cup' },
      { label: '逻辑或', latex: '\\vee' },
      { label: '逻辑与', latex: '\\wedge' },
      { label: '先于', latex: '\\prec' },
      { label: '后于', latex: '\\succ' },
      { label: '先于等于', latex: '\\preceq' },
      { label: '后于等于', latex: '\\succeq' },
      { label: '集合差', latex: '\\setminus' },
      { label: '左三角', latex: '\\triangleleft' },
      { label: '右三角', latex: '\\triangleright' },
      { label: '上三角', latex: '\\bigtriangleup' },
      { label: '下三角', latex: '\\bigtriangledown' },
      { label: '复合（函数）', latex: '\\circ' },
      { label: '乘法（叉）', latex: '\\times' },
      { label: '除法（斜线）', latex: '/' },
      { label: '加减符（正负）', latex: '\\pm' },
    ],
  },
  {
    key: 'arrows',
    title: '箭头',
    items: [
      { label: '向右箭头', latex: '\\rightarrow' },
      { label: '向左箭头', latex: '\\leftarrow' },
      { label: '左右双向箭头', latex: '\\leftrightarrow' },
      { label: '向右推导', latex: '\\Rightarrow' },
      { label: '向左推导', latex: '\\Leftarrow' },
      { label: '等价推导', latex: '\\Leftrightarrow' },
      { label: '映射', latex: '\\mapsto' },
      { label: '长映射', latex: '\\longmapsto' },
      { label: '长右箭头', latex: '\\longrightarrow' },
      { label: '长左箭头', latex: '\\longleftarrow' },
      { label: '长双向箭头', latex: '\\longleftrightarrow' },
      { label: '上箭头', latex: '\\uparrow' },
      { label: '下箭头', latex: '\\downarrow' },
      { label: '上下箭头', latex: '\\updownarrow' },
      { label: '东北箭头', latex: '\\nearrow' },
      { label: '东南箭头', latex: '\\searrow' },
      { label: '西南箭头', latex: '\\swarrow' },
      { label: '西北箭头', latex: '\\nwarrow' },
      { label: '嵌入（右）', latex: '\\hookrightarrow' },
      { label: '嵌入（左）', latex: '\\hookleftarrow' },
      { label: '满射', latex: '\\twoheadrightarrow' },
      { label: '单射', latex: '\\rightarrowtail' },
      { label: '右半鱼叉', latex: '\\rightharpoonup' },
      { label: '右半鱼叉（下）', latex: '\\rightharpoondown' },
      { label: '可逆反应（鱼叉）', latex: '\\rightleftharpoons' },
      { label: '可逆（左鱼叉）', latex: '\\leftrightharpoons' },
      { label: '右双箭头', latex: '\\rightrightarrows' },
      { label: '左双箭头', latex: '\\leftleftarrows' },
      { label: '左右双箭头', latex: '\\rightleftarrows' },
      { label: '波浪右箭头', latex: '\\rightsquigarrow' },
      { label: '波浪右箭头（细）', latex: '\\leadsto' },
      { label: '弧线右箭头', latex: '\\curvearrowright' },
      { label: '弧线左箭头', latex: '\\curvearrowleft' },
      { label: '环形右箭头', latex: '\\circlearrowright' },
      { label: '环形左箭头', latex: '\\circlearrowleft' },
      { label: '双上箭头', latex: '\\upuparrows' },
      { label: '双下箭头', latex: '\\downdownarrows' },
      { label: '右长双箭头', latex: '\\Rrightarrow' },
      { label: '左长双箭头', latex: '\\Lleftarrow' },
      { label: '推出', latex: '\\implies' },
      { label: '被推出', latex: '\\impliedby' },
      { label: '当且仅当', latex: '\\iff' },
      { label: '上方可带文字的长箭头', latex: `\\xrightarrow{${P}}`, preview: '\\xrightarrow{\\Delta}' },
      { label: '下方可带文字的长箭头', latex: `\\xleftarrow{${P}}`, preview: '\\xleftarrow{n}' },
      { label: '上下可带文字的长箭头', latex: `\\xrightarrow[${P}]{${P}}`, preview: '\\xrightarrow[\\text{吸热}]{催化剂}' },
    ],
  },
  {
    key: 'negated',
    title: '求反运算符',
    items: [
      { label: '不等于', latex: '\\neq' },
      { label: '不小于', latex: '\\nless' },
      { label: '不大于', latex: '\\ngtr' },
      { label: '不小于等于', latex: '\\nleq' },
      { label: '不大于等于', latex: '\\ngeq' },
      { label: '不小于等于（倾斜）', latex: '\\nleqslant' },
      { label: '不大于等于（倾斜）', latex: '\\ngeqslant' },
      { label: '不恒等于', latex: '\\not\\equiv' },
      { label: '不约等于', latex: '\\not\\approx' },
      { label: '不相似', latex: '\\nsim' },
      { label: '不全等', latex: '\\ncong' },
      { label: '不是子集', latex: '\\not\\subset' },
      { label: '不是超集', latex: '\\not\\supset' },
      { label: '不是子集（含等于）', latex: '\\nsubseteq' },
      { label: '不是超集（含等于）', latex: '\\nsupseteq' },
      { label: '不属于', latex: '\\notin' },
      { label: '不存在', latex: '\\nexists' },
      { label: '不整除', latex: '\\nmid' },
      { label: '不平行', latex: '\\nparallel' },
      { label: '不先于', latex: '\\nprec' },
      { label: '不后于', latex: '\\nsucc' },
      { label: '不能推出', latex: '\\nrightarrow' },
      { label: '不能被推出', latex: '\\nleftarrow' },
      { label: '不能反推', latex: '\\nLeftarrow' },
      { label: '不等价', latex: '\\nLeftrightarrow' },
      { label: '不可推出', latex: '\\nvdash' },
    ],
  },
  {
    key: 'accents',
    title: '音标与修饰',
    items: [
      { label: '向量 a', latex: `\\vec{${P}}`, preview: '\\vec{a}' },
      { label: '向量 AB', latex: `\\overrightarrow{${P}}`, preview: '\\overrightarrow{AB}' },
      { label: '反向向量 AB', latex: `\\overleftarrow{${P}}`, preview: '\\overleftarrow{AB}' },
      { label: '双向向量', latex: `\\overleftrightarrow{${P}}`, preview: '\\overleftrightarrow{AB}' },
      { label: '尖帽（单字符）', latex: `\\hat{${P}}`, preview: '\\hat{a}' },
      { label: '尖帽（多字符）', latex: `\\widehat{${P}}`, preview: '\\widehat{ABC}' },
      { label: '横线（单字符）', latex: `\\bar{${P}}`, preview: '\\bar{x}' },
      { label: '上划线', latex: `\\overline{${P}}`, preview: '\\overline{AB}' },
      { label: '下划线', latex: `\\underline{${P}}`, preview: '\\underline{AB}' },
      { label: '波浪（单字符）', latex: `\\tilde{${P}}`, preview: '\\tilde{n}' },
      { label: '波浪（多字符）', latex: `\\widetilde{${P}}`, preview: '\\widetilde{ABC}' },
      { label: '一阶点', latex: `\\dot{${P}}`, preview: '\\dot{y}' },
      { label: '二阶点', latex: `\\ddot{${P}}`, preview: '\\ddot{y}' },
      { label: '尖音符', latex: `\\acute{${P}}`, preview: '\\acute{a}' },
      { label: '钝音符', latex: `\\grave{${P}}`, preview: '\\grave{a}' },
      { label: '抑扬符', latex: `\\check{${P}}`, preview: '\\check{a}' },
      { label: '短音符', latex: `\\breve{${P}}`, preview: '\\breve{a}' },
      { label: '空心圆', latex: `\\mathring{${P}}`, preview: '\\mathring{A}' },
      { label: '上花括号（带注释）', latex: `\\overbrace{${P}}^{${P}}`, preview: '\\overbrace{a+b}^{n}' },
      { label: '下花括号（带注释）', latex: `\\underbrace{${P}}_{${P}}`, preview: '\\underbrace{a+b}_{n}' },
      { label: '上方加符号', latex: `\\overset{${P}}{${P}}`, preview: '\\overset{?}{=}' },
      { label: '下方加符号', latex: `\\underset{${P}}{${P}}`, preview: '\\underset{n \\to \\infty}{\\lim}' },
      { label: '上下加符号（关系）', latex: `\\stackrel{${P}}{${P}}`, preview: '\\stackrel{\\text{def}}{=}' },
      { label: '加框', latex: `\\boxed{${P}}`, preview: '\\boxed{x}' },
      /* \text 是文本模式，\square 占位符在文本模式下非法，故直接插入可改写的中文示例 */
      { label: '文本', latex: '\\text{文字}', preview: '\\text{文字}' },
      { label: '正体（罗马体）', latex: `\\mathrm{${P}}`, preview: '\\mathrm{d}' },
      { label: '自定义算子', latex: `\\operatorname{${P}}`, preview: '\\operatorname{arcsinh}' },
    ],
  },
  {
    key: 'geometry',
    title: '几何学',
    items: [
      { label: '角', latex: '\\angle' },
      { label: '角的度量', latex: '\\measuredangle' },
      { label: '球面角', latex: '\\sphericalangle' },
      { label: '三角形', latex: '\\triangle' },
      { label: '三角形（细）', latex: '\\vartriangle' },
      { label: '倒三角', latex: '\\triangledown' },
      { label: '实心三角', latex: '\\blacktriangle' },
      { label: '全等', latex: '\\cong' },
      { label: '相似', latex: '\\sim' },
      { label: '平行', latex: '\\parallel' },
      { label: '不平行', latex: '\\nparallel' },
      { label: '垂直', latex: '\\perp' },
      { label: '正方形', latex: '\\square' },
      { label: '实心方块', latex: '\\blacksquare' },
      { label: '菱形', latex: '\\lozenge' },
      { label: '实心菱形', latex: '\\blacklozenge' },
      { label: '圆', latex: '\\bigcirc' },
      { label: '圆心点（⊙O）', latex: '\\odot' },
      { label: '弧 AB', latex: `\\overset{\\frown}{${P}}`, preview: '\\overset{\\frown}{AB}' },
      { label: '弧 AB（长弧）', latex: `\\overset{\\frown}{${P} B}`, preview: '\\overset{\\frown}{AB}' },
      { label: '角 ABC', latex: '\\angle ABC' },
      { label: '三角形 ABC', latex: '\\triangle ABC' },
      { label: '三角形面积', latex: 'S_{\\triangle ABC}' },
      { label: '线段 AB', latex: 'AB' },
      { label: '度', latex: '^{\\circ}' },
      { label: '分（角分）', latex: "'" },
      { label: '秒（角秒）', latex: "''" },
      { label: '所以', latex: '\\therefore' },
      { label: '因为', latex: '\\because' },
    ],
  },
  {
    key: 'fraction',
    title: '分数',
    items: [
      { label: '分数模板', latex: `\\frac{${P}}{${P}}`, preview: '\\frac{a}{b}' },
      { label: 'display 分数模板', latex: `\\dfrac{${P}}{${P}}`, preview: '\\dfrac{a}{b}' },
      { label: 'text 分数模板', latex: `\\tfrac{${P}}{${P}}`, preview: '\\tfrac{a}{b}' },
      { label: '连分数模板', latex: `\\cfrac{${P}}{${P}}`, preview: '\\cfrac{1}{1+\\cfrac{1}{x}}' },
      { label: '繁分数示例', latex: '\\dfrac{\\dfrac{a}{b}}{\\dfrac{c}{d}}' },
      { label: '带分数（二又三分之一）', latex: '2\\dfrac{1}{3}' },
      { label: '常用分数：二分之一', latex: '\\frac{1}{2}' },
      { label: '常用分数：三分之一', latex: '\\frac{1}{3}' },
      { label: '常用分数：三分之二', latex: '\\frac{2}{3}' },
      { label: '常用分数：四分之一', latex: '\\frac{1}{4}' },
      { label: '常用分数：四分之三', latex: '\\frac{3}{4}' },
      { label: '常用分数：五分之一', latex: '\\frac{1}{5}' },
      { label: '百分数模板', latex: `\\frac{${P}}{100}`, preview: '\\frac{20}{100}' },
      { label: '分数与百分号', latex: '\\frac{a}{b} \\times 100\\%' },
      { label: '分式示例', latex: '\\frac{x+1}{x-1}' },
      { label: '分数（含根式）', latex: '\\frac{1}{\\sqrt{2}}' },
    ],
  },
  {
    key: 'supsub',
    title: '上下标',
    items: [
      { label: '上标模板', latex: `x^{${P}}`, preview: 'x^{n}' },
      { label: '下标模板', latex: `x_{${P}}`, preview: 'x_{n}' },
      { label: '上下标模板', latex: `x_{${P}}^{${P}}`, preview: 'x_{i}^{2}' },
      { label: '平方', latex: 'x^{2}' },
      { label: '立方', latex: 'x^{3}' },
      { label: 'n 次方', latex: 'x^{n}' },
      { label: '负一次方', latex: 'x^{-1}' },
      { label: '下标 i', latex: 'x_{i}' },
      { label: '双下标', latex: 'x_{i,j}' },
      { label: '下标 n+1', latex: 'x_{n+1}' },
      { label: '上标含分数', latex: `a^{\\frac{${P}}{${P}}}`, preview: 'a^{\\frac{m}{n}}' },
      { label: '下标记号', latex: 'a_{1}' },
      { label: 'e 的幂', latex: `e^{${P}}`, preview: 'e^{x}' },
      { label: 'e 的负幂', latex: 'e^{-x}' },
      { label: '阿伦尼乌斯指数', latex: 'e^{-\\frac{E_{\\mathrm{a}}}{RT}}' },
      { label: '指数函数模板', latex: `a^{${P}}`, preview: 'a^{x}' },
      { label: '底数可换的对数下标', latex: `\\log_{${P}}`, preview: '\\log_{a}' },
      { label: '同位素标记', latex: `{}^{${P}}_{${P}}\\mathrm{X}`, preview: '{}^{235}_{92}\\mathrm{U}' },
      { label: '排列数下标', latex: 'A_{n}^{m}' },
      { label: '组合数下标', latex: 'C_{n}^{m}' },
    ],
  },
  {
    key: 'radical',
    title: '根式',
    items: [
      { label: '平方根模板', latex: `\\sqrt{${P}}`, preview: '\\sqrt{x}' },
      { label: 'n 次根式模板', latex: `\\sqrt[${P}]{${P}}`, preview: '\\sqrt[3]{x}' },
      { label: '根号内分数', latex: `\\sqrt{\\frac{${P}}{${P}}}`, preview: '\\sqrt{\\frac{a}{b}}' },
      { label: '根式在分母', latex: `\\frac{1}{\\sqrt{${P}}}`, preview: '\\frac{1}{\\sqrt{x}}' },
      { label: '根号下带平方', latex: '\\sqrt{x^{2}+y^{2}}' },
      { label: '常用根号 2', latex: '\\sqrt{2}' },
      { label: '常用根号 3', latex: '\\sqrt{3}' },
      { label: '立方根', latex: '\\sqrt[3]{x}' },
      { label: 'n 次方根（一般式）', latex: '\\sqrt[n]{a^{m}}' },
      { label: '勾股定理', latex: 'a^{2}+b^{2}=c^{2}' },
      { label: '点距离公式', latex: '\\sqrt{(x_{2}-x_{1})^{2}+(y_{2}-y_{1})^{2}}' },
      { label: '判别式', latex: '\\sqrt{b^{2}-4ac}' },
      { label: '求根公式', latex: 'x = \\frac{-b \\pm \\sqrt{b^{2}-4ac}}{2a}' },
    ],
  },
  {
    key: 'integral',
    title: '积分',
    items: [
      { label: '不定积分号', latex: '\\int' },
      { label: '二重积分号', latex: '\\iint' },
      { label: '三重积分号', latex: '\\iiint' },
      { label: '曲线积分号', latex: '\\oint' },
      { label: '曲面积分号', latex: '\\oiint' },
      { label: '小积分号', latex: '\\smallint' },
      { label: '定积分模板', latex: `\\int_{${P}}^{${P}}`, preview: '\\int_{a}^{b}' },
      { label: '定积分（含被积函数）', latex: `\\int_{${P}}^{${P}} ${P}\\,dx`, preview: '\\int_{a}^{b} f(x)\\,dx' },
      { label: '二重积分模板', latex: `\\iint_{${P}} ${P}\\,d\\sigma`, preview: '\\iint_{D} f(x,y)\\,d\\sigma' },
      { label: '三重积分模板', latex: `\\iiint_{\\Omega} ${P}\\,dV`, preview: '\\iiint_{\\Omega} f(x,y,z)\\,dV' },
      { label: '闭合曲线积分', latex: `\\oint_{${P}} ${P}\\,dz`, preview: '\\oint_{L} f(z)\\,dz' },
      { label: '高斯公式（闭合曲面）', latex: '\\oiint_{S} \\vec{F} \\cdot d\\vec{S}' },
      { label: '牛顿-莱布尼茨公式', latex: '\\int_{a}^{b} f(x)\\,dx = F(b)-F(a)' },
      { label: '面积分（曲面）', latex: '\\iint_{D} \\sqrt{1+z_{x}^{2}+z_{y}^{2}}\\,dx\\,dy' },
      { label: '常用积分示例', latex: '\\int_{0}^{+\\infty} e^{-x^{2}}\\,dx = \\frac{\\sqrt{\\pi}}{2}' },
      { label: '1/x 积分', latex: '\\int \\frac{1}{x}\\,dx = \\ln\\left\\vert x \\right\\vert + C' },
      { label: '幂函数积分', latex: '\\int x^{n}\\,dx = \\frac{x^{n+1}}{n+1} + C' },
      { label: '分部积分', latex: '\\int u\\,dv = uv - \\int v\\,du' },
      { label: '积分上限函数', latex: 'F(x) = \\int_{a}^{x} f(t)\\,dt' },
    ],
  },
  {
    key: 'derivatives',
    title: '导数与微分',
    items: [
      { label: '一阶导数 dy/dx', latex: '\\frac{dy}{dx}' },
      { label: '二阶导数', latex: '\\frac{d^{2}y}{dx^{2}}' },
      { label: 'n 阶导数', latex: '\\frac{d^{n}y}{dx^{n}}' },
      { label: '导数算子 d/dx', latex: `\\frac{d}{dx}${P}`, preview: '\\frac{d}{dx}f(x)' },
      { label: "拉格朗日记法 y'", latex: "y'" },
      { label: '二阶（撇记）', latex: "y''" },
      { label: '牛顿点记一阶', latex: '\\dot{y}' },
      { label: '牛顿点记二阶', latex: '\\ddot{y}' },
      { label: '偏导模板', latex: `\\frac{\\partial}{\\partial x}${P}`, preview: '\\frac{\\partial}{\\partial x}f' },
      { label: '一阶偏导', latex: '\\frac{\\partial f}{\\partial x}' },
      { label: '二阶偏导', latex: '\\frac{\\partial^{2} f}{\\partial x^{2}}' },
      { label: '混合偏导', latex: '\\frac{\\partial^{2} f}{\\partial x \\partial y}' },
      { label: '偏微分号', latex: '\\partial' },
      { label: '全微分', latex: 'dz = \\frac{\\partial z}{\\partial x}dx + \\frac{\\partial z}{\\partial y}dy' },
      { label: '梯度（nabla）', latex: '\\nabla' },
      { label: '梯度作用于 f', latex: '\\nabla f' },
      { label: '散度', latex: '\\nabla \\cdot \\vec{F}' },
      { label: '旋度', latex: '\\nabla \\times \\vec{F}' },
      { label: '拉普拉斯算子', latex: '\\nabla^{2}' },
      { label: '增量 Δy', latex: '\\Delta y' },
      { label: '增量 Δx', latex: '\\Delta x' },
      { label: '微分 dy', latex: 'dy' },
      { label: '导数定义式', latex: "f'(x) = \\lim_{\\Delta x \\to 0} \\frac{f(x+\\Delta x)-f(x)}{\\Delta x}" },
      { label: '泰勒展开', latex: 'f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^{n}' },
    ],
  },
  {
    key: 'bigops',
    title: '大型运算符',
    items: [
      { label: '求和号', latex: '\\sum' },
      { label: '求积号', latex: '\\prod' },
      { label: '余积号', latex: '\\coprod' },
      { label: '并集大号', latex: '\\bigcup' },
      { label: '交集大号', latex: '\\bigcap' },
      { label: '环加大号', latex: '\\bigoplus' },
      { label: '环乘大号', latex: '\\bigotimes' },
      { label: '环点大号', latex: '\\bigodot' },
      { label: '方形并', latex: '\\bigsqcup' },
      { label: '多重集并大号', latex: '\\biguplus' },
      { label: '析取大号', latex: '\\bigvee' },
      { label: '合取大号', latex: '\\bigwedge' },
      { label: '连加（i 从 1 到 n）', latex: '\\sum_{i=1}^{n}' },
      { label: '连乘（i 从 1 到 n）', latex: '\\prod_{i=1}^{n}' },
      { label: '连加（到无穷）', latex: '\\sum_{n=1}^{\\infty}' },
      { label: '连加（含通项）', latex: '\\sum_{i=1}^{n} a_{i}' },
      { label: '并集（i 从 1 到 n）', latex: '\\bigcup_{i=1}^{n}' },
      { label: '交集（i 从 1 到 n）', latex: '\\bigcap_{i=1}^{n}' },
      { label: '等比级数求和', latex: '\\sum_{n=0}^{\\infty} \\frac{1}{2^{n}} = 2' },
      { label: 'p 级数', latex: '\\sum_{n=1}^{\\infty} \\frac{1}{n^{2}} = \\frac{\\pi^{2}}{6}' },
      { label: '求和下限自定义', latex: `\\sum_{${P}=${P}}^{${P}}`, preview: '\\sum_{k=0}^{n}' },
    ],
  },
  {
    key: 'brackets',
    title: '括号与分段',
    items: [
      { label: '圆括号（随内容伸缩）', latex: `\\left( ${P} \\right)`, preview: '\\left( x \\right)' },
      { label: '方括号（随内容伸缩）', latex: `\\left[ ${P} \\right]`, preview: '\\left[ x \\right]' },
      { label: '花括号（随内容伸缩）', latex: `\\left\\{ ${P} \\right\\}`, preview: '\\left\\{ x \\right\\}' },
      { label: '圆括号（含分式）', latex: `\\left( \\frac{${P}}{${P}} \\right)`, preview: '\\left( \\frac{a}{b} \\right)' },
      { label: '方括号（含分式）', latex: `\\left[ \\frac{${P}}{${P}} \\right]`, preview: '\\left[ \\frac{a}{b} \\right]' },
      { label: '花括号（含分式）', latex: `\\left\\{ \\frac{${P}}{${P}} \\right\\}`, preview: '\\left\\{ \\frac{a}{b} \\right\\}' },
      { label: '括号后带幂', latex: `\\left( ${P} \\right)^{${P}}`, preview: '\\left( \\frac{a}{b} \\right)^{n}' },
      { label: '上取整', latex: `\\lceil ${P} \\rceil`, preview: '\\lceil x \\rceil' },
      { label: '下取整', latex: `\\lfloor ${P} \\rfloor`, preview: '\\lfloor x \\rfloor' },
      { label: '内积尖括号', latex: `\\langle ${P} \\rangle`, preview: '\\langle x, y \\rangle' },
      { label: '绝对值', latex: `\\left\\vert ${P} \\right\\vert`, preview: '\\left\\vert x \\right\\vert' },
      { label: '范数（双竖线）', latex: `\\left\\Vert ${P} \\right\\Vert`, preview: '\\left\\Vert \\vec{a} \\right\\Vert' },
      { label: '闭区间', latex: `\\left[ ${P}, ${P} \\right]`, preview: '\\left[ a, b \\right]' },
      { label: '开区间', latex: `\\left( ${P}, ${P} \\right)`, preview: '\\left( a, b \\right)' },
      { label: '左闭右开区间', latex: `\\left[ ${P}, ${P} \\right)`, preview: '\\left[ a, b \\right)' },
      { label: '分段函数（cases）', latex: `\\begin{cases} ${P} & ${P} \\\\ ${P} & ${P} \\end{cases}`, preview: '\\begin{cases} x & x \\ge 0 \\\\ -x & x \\lt 0 \\end{cases}' },
      { label: '分段函数（三行）', latex: `\\begin{cases} ${P} & ${P} \\\\ ${P} & ${P} \\\\ ${P} & ${P} \\end{cases}`, preview: '\\begin{cases} 1 & x \\gt 0 \\\\ 0 & x = 0 \\\\ -1 & x \\lt 0 \\end{cases}' },
      { label: '方程组', latex: `\\begin{cases} ${P} \\\\ ${P} \\end{cases}`, preview: '\\begin{cases} x+y=3 \\\\ x-y=1 \\end{cases}' },
      { label: '嵌套括号', latex: '\\left[ \\left( a+b \\right)c + d \\right]^{2}' },
    ],
  },
  {
    key: 'functions',
    title: '函数与三角',
    items: [
      { label: '正弦', latex: '\\sin' },
      { label: '余弦', latex: '\\cos' },
      { label: '正切', latex: '\\tan' },
      { label: '余切', latex: '\\cot' },
      { label: '正割', latex: '\\sec' },
      { label: '余割', latex: '\\csc' },
      { label: '反正弦', latex: '\\arcsin' },
      { label: '反余弦', latex: '\\arccos' },
      { label: '反正切', latex: '\\arctan' },
      { label: '双曲正弦', latex: '\\sinh' },
      { label: '双曲余弦', latex: '\\cosh' },
      { label: '双曲正切', latex: '\\tanh' },
      { label: '双曲余切', latex: '\\coth' },
      { label: '正弦函数 sinθ', latex: '\\sin\\theta' },
      { label: '余弦函数 cosθ', latex: '\\cos\\theta' },
      { label: '正切函数 tanθ', latex: '\\tan\\theta' },
      { label: '正弦平方', latex: '\\sin^{2}\\theta' },
      { label: '三角恒等式', latex: '\\sin^{2}\\theta + \\cos^{2}\\theta = 1' },
      { label: '两角和正弦', latex: '\\sin(\\alpha+\\beta) = \\sin\\alpha\\cos\\beta + \\cos\\alpha\\sin\\beta' },
      { label: '二倍角余弦', latex: '\\cos 2\\theta = 2\\cos^{2}\\theta - 1' },
      { label: '正弦定理', latex: '\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C} = 2R' },
      { label: '余弦定理', latex: 'c^{2} = a^{2} + b^{2} - 2ab\\cos C' },
      { label: '最大值', latex: '\\max' },
      { label: '最小值', latex: '\\min' },
      { label: '上确界', latex: '\\sup' },
      { label: '下确界', latex: '\\inf' },
      { label: '指数函数', latex: '\\exp' },
      { label: '对数（log）', latex: '\\log' },
      { label: '自然对数', latex: '\\ln' },
      { label: '常用对数（10 为底）', latex: '\\lg' },
      { label: '行列式', latex: '\\det' },
      { label: '最大公约数', latex: '\\gcd' },
      { label: '最小公倍数', latex: '\\operatorname{lcm}' },
      { label: '取整函数', latex: '\\operatorname{sgn}' },
      { label: '阶乘', latex: 'n!' },
      { label: '伽马函数', latex: '\\Gamma(n) = (n-1)!' },
    ],
  },
  {
    key: 'limits',
    title: '极限与对数',
    items: [
      { label: '极限号', latex: '\\lim' },
      { label: '极限（x 趋于占位）', latex: `\\lim_{x \\to ${P}}`, preview: '\\lim_{x \\to a}' },
      { label: '极限（x 趋于 0）', latex: '\\lim_{x \\to 0}' },
      { label: '极限（x 趋于无穷）', latex: '\\lim_{x \\to \\infty}' },
      { label: '极限（n 趋于无穷）', latex: '\\lim_{n \\to \\infty}' },
      { label: '极限（x 趋于正无穷）', latex: '\\lim_{x \\to +\\infty}' },
      { label: '下极限', latex: '\\liminf' },
      { label: '上极限', latex: '\\limsup' },
      { label: '重要极限（sin x / x）', latex: '\\lim_{x \\to 0} \\frac{\\sin x}{x} = 1' },
      { label: '重要极限（1+1/n）', latex: '\\lim_{n \\to \\infty} \\left( 1 + \\frac{1}{n} \\right)^{n} = e' },
      { label: '洛必达法则形式', latex: '\\lim_{x \\to a} \\frac{f(x)}{g(x)} = \\lim_{x \\to a} \\frac{f\'(x)}{g\'(x)}' },
      { label: '对数（log）', latex: '\\log' },
      { label: '换底对数模板', latex: `\\log_{${P}} ${P}`, preview: '\\log_{a} x' },
      { label: '换底公式', latex: '\\log_{a} b = \\frac{\\log_{c} b}{\\log_{c} a}' },
      { label: '自然对数模板', latex: `\\ln ${P}`, preview: '\\ln x' },
      { label: '常用对数模板', latex: `\\lg ${P}`, preview: '\\lg x' },
      { label: '对数运算法则', latex: '\\log_{a}(MN) = \\log_{a} M + \\log_{a} N' },
      { label: '对数恒等式', latex: 'a^{\\log_{a} N} = N' },
      { label: '无穷小记号', latex: 'o(x)' },
      { label: '复杂度记号', latex: '\\mathcal{O}(n)' },
      { label: 'e 的极限定义', latex: 'e = \\lim_{n \\to \\infty} \\left( 1 + \\frac{1}{n} \\right)^{n}' },
    ],
  },
  {
    key: 'combinatorics',
    title: '排列组合与统计',
    items: [
      { label: '组合数模板', latex: `\\binom{${P}}{${P}}`, preview: '\\binom{n}{k}' },
      { label: '组合数（display）', latex: `\\dbinom{${P}}{${P}}`, preview: '\\dbinom{n}{k}' },
      { label: '组合数（text）', latex: `\\tbinom{${P}}{${P}}`, preview: '\\tbinom{n}{k}' },
      { label: '排列数', latex: 'A_{n}^{m}' },
      { label: '组合数（C 记法）', latex: 'C_{n}^{m}' },
      { label: '阶乘', latex: 'n!' },
      { label: '组合数展开式', latex: '\\binom{n}{k} = \\frac{n!}{k!(n-k)!}' },
      { label: '二项式定理', latex: '(a+b)^{n} = \\sum_{k=0}^{n} \\binom{n}{k} a^{n-k}b^{k}' },
      { label: '事件概率', latex: 'P(A) = \\frac{m}{n}' },
      { label: '对立事件', latex: 'P(\\overline{A}) = 1 - P(A)' },
      { label: '条件概率', latex: 'P(B \\mid A) = \\frac{P(AB)}{P(A)}' },
      { label: '相互独立', latex: 'P(AB) = P(A)P(B)' },
      { label: '全概率公式', latex: 'P(B) = \\sum_{i=1}^{n} P(A_{i})P(B \\mid A_{i})' },
      { label: '数学期望', latex: 'E(X) = \\sum_{i=1}^{n} x_{i}p_{i}' },
      { label: '方差', latex: 'D(X) = E(X^{2}) - \\left( E(X) \\right)^{2}' },
      { label: '标准差', latex: '\\sigma = \\sqrt{D(X)}' },
      { label: '二项分布', latex: 'X \\sim B(n,p)' },
      { label: '正态分布', latex: 'X \\sim N(\\mu, \\sigma^{2})' },
      { label: '超几何分布', latex: 'P(X=k) = \\frac{C_{M}^{k}C_{N-M}^{n-k}}{C_{N}^{n}}' },
      { label: '平均数', latex: '\\overline{x} = \\frac{1}{n}\\sum_{i=1}^{n} x_{i}' },
      { label: '样本方差', latex: 's^{2} = \\frac{1}{n}\\sum_{i=1}^{n}(x_{i}-\\overline{x})^{2}' },
      { label: '线性回归方程', latex: '\\hat{y} = \\hat{b}x + \\hat{a}' },
      { label: '卡方统计量', latex: '\\chi^{2} = \\frac{n(ad-bc)^{2}}{(a+b)(c+d)(a+c)(b+d)}' },
      { label: '相关系数', latex: 'r = \\frac{\\sum (x_{i}-\\bar{x})(y_{i}-\\bar{y})}{\\sqrt{\\sum (x_{i}-\\bar{x})^{2}\\sum (y_{i}-\\bar{y})^{2}}}' },
    ],
  },
  {
    key: 'series',
    title: '数列与级数',
    items: [
      { label: '数列通项', latex: 'a_{n}' },
      { label: '前 n 项和', latex: 'S_{n}' },
      { label: '等差数列通项', latex: 'a_{n} = a_{1} + (n-1)d' },
      { label: '等差数列求和', latex: 'S_{n} = \\frac{n(a_{1}+a_{n})}{2}' },
      { label: '等比数列通项', latex: 'a_{n} = a_{1}q^{n-1}' },
      { label: '等比数列求和', latex: 'S_{n} = \\frac{a_{1}(1-q^{n})}{1-q}' },
      { label: '等比中项', latex: 'b^{2} = ac' },
      { label: '递推式', latex: 'a_{n+1} = a_{n} + d' },
      { label: '裂项相消', latex: '\\frac{1}{n(n+1)} = \\frac{1}{n} - \\frac{1}{n+1}' },
      { label: '无穷级数', latex: '\\sum_{n=1}^{\\infty} a_{n}' },
      { label: '极限（部分和）', latex: '\\lim_{n \\to \\infty} S_{n}' },
      { label: '数列极限定义', latex: '\\lim_{n \\to \\infty} a_{n} = A' },
      { label: '调和级数', latex: '\\sum_{n=1}^{\\infty} \\frac{1}{n}' },
      { label: '交错级数', latex: '\\sum_{n=1}^{\\infty} (-1)^{n+1}\\frac{1}{n}' },
      { label: '几何级数求和公式', latex: '\\sum_{n=0}^{\\infty} q^{n} = \\frac{1}{1-q} \\quad (\\left\\vert q \\right\\vert \\lt 1)' },
    ],
  },
  {
    key: 'matrix',
    title: '矩阵与方程组',
    items: [
      { label: '圆括号矩阵 2×2', latex: `\\begin{pmatrix} ${P} & ${P} \\\\ ${P} & ${P} \\end{pmatrix}`, preview: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}' },
      { label: '方括号矩阵 2×2', latex: `\\begin{bmatrix} ${P} & ${P} \\\\ ${P} & ${P} \\end{bmatrix}`, preview: '\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}' },
      { label: '花括号矩阵 2×2', latex: `\\begin{Bmatrix} ${P} & ${P} \\\\ ${P} & ${P} \\end{Bmatrix}`, preview: '\\begin{Bmatrix} a & b \\\\ c & d \\end{Bmatrix}' },
      { label: '行列式 2×2', latex: `\\begin{vmatrix} ${P} & ${P} \\\\ ${P} & ${P} \\end{vmatrix}`, preview: '\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}' },
      { label: '范数矩阵 2×2', latex: `\\begin{Vmatrix} ${P} & ${P} \\\\ ${P} & ${P} \\end{Vmatrix}`, preview: '\\begin{Vmatrix} a & b \\\\ c & d \\end{Vmatrix}' },
      { label: '圆括号矩阵 3×3', latex: `\\begin{pmatrix} ${P} & ${P} & ${P} \\\\ ${P} & ${P} & ${P} \\\\ ${P} & ${P} & ${P} \\end{pmatrix}`, preview: '\\begin{pmatrix} a & b & c \\\\ d & e & f \\\\ g & h & i \\end{pmatrix}' },
      { label: '方括号矩阵 3×3', latex: `\\begin{bmatrix} ${P} & ${P} & ${P} \\\\ ${P} & ${P} & ${P} \\\\ ${P} & ${P} & ${P} \\end{bmatrix}`, preview: '\\begin{bmatrix} a & b & c \\\\ d & e & f \\\\ g & h & i \\end{bmatrix}' },
      { label: '列向量（2 行）', latex: `\\begin{pmatrix} ${P} \\\\ ${P} \\end{pmatrix}`, preview: '\\begin{pmatrix} x \\\\ y \\end{pmatrix}' },
      { label: '行向量（1×3）', latex: `\\begin{pmatrix} ${P} & ${P} & ${P} \\end{pmatrix}`, preview: '\\begin{pmatrix} x & y & z \\end{pmatrix}' },
      { label: '省略矩阵', latex: `\\begin{pmatrix} ${P} & \\cdots & ${P} \\\\ \\vdots & \\ddots & \\vdots \\\\ ${P} & \\cdots & ${P} \\end{pmatrix}`, preview: '\\begin{pmatrix} a_{11} & \\cdots & a_{1n} \\\\ \\vdots & \\ddots & \\vdots \\\\ a_{n1} & \\cdots & a_{nn} \\end{pmatrix}' },
      { label: '矩阵转置', latex: 'A^{\\mathrm{T}}' },
      { label: '逆矩阵', latex: 'A^{-1}' },
      { label: '行列式', latex: '\\det A' },
      { label: '矩阵乘法', latex: 'AB = C_{m \\times n}' },
      { label: '单位矩阵', latex: '\\mathrm{I}_{n}' },
      { label: '增广矩阵', latex: `\\left( \\begin{array}{cc|c} ${P} & ${P} & ${P} \\\\ ${P} & ${P} & ${P} \\end{array} \\right)`, preview: '\\left( \\begin{array}{cc|c} 1 & 2 & 3 \\\\ 4 & 5 & 6 \\end{array} \\right)' },
      { label: '表格（带竖线）', latex: `\\begin{array}{c|c} ${P} & ${P} \\\\ \\hline ${P} & ${P} \\end{array}`, preview: '\\begin{array}{c|c} 1 & 2 \\\\ \\hline 3 & 4 \\end{array}' },
    ],
  },
  {
    key: 'layout',
    title: '排版与间距',
    items: [
      { label: '宽空格', latex: '\\quad' },
      { label: '更宽空格', latex: '\\qquad' },
      { label: '中等空格', latex: '\\;' },
      { label: '窄空格', latex: '\\,' },
      { label: '负空格（收紧）', latex: '\\!' },
      { label: '换行', latex: '\\\\' },
      { label: '正体文本', latex: '\\text{文字}', preview: '\\text{文字}' },
      { label: '强制显示样式', latex: '\\displaystyle' },
      { label: '强制行内样式', latex: '\\textstyle' },
      { label: '多行对齐（等号对齐）', latex: `\\begin{aligned} ${P} &= ${P} \\\\ ${P} &= ${P} \\end{aligned}`, preview: '\\begin{aligned} x &= 1 \\\\ y &= 2 \\end{aligned}' },
      { label: '多行对齐（三行）', latex: `\\begin{aligned} ${P} &= ${P} \\\\ ${P} &= ${P} \\\\ ${P} &= ${P} \\end{aligned}`, preview: '\\begin{aligned} a &= b + c \\\\ d &= e + f \\\\ g &= h + i \\end{aligned}' },
      { label: '推导过程（带说明）', latex: `\\begin{aligned} ${P} &= ${P} && \\text{说明} \\\\ ${P} &= ${P} && \\text{说明} \\end{aligned}`, preview: '\\begin{aligned} x &= 1 && \\text{代入} \\\\ y &= 2 && \\text{化简} \\end{aligned}' },
      { label: '居中排列（gathered）', latex: `\\begin{gathered} ${P} \\\\ ${P} \\end{gathered}`, preview: '\\begin{gathered} x = 1 \\\\ y = 2 \\end{gathered}' },
      { label: '红色强调', latex: `{\\color{red} ${P}}`, preview: '{\\color{red} x}' },
      { label: '蓝色强调', latex: `{\\color{blue} ${P}}`, preview: '{\\color{blue} x}' },
      { label: '绿色强调', latex: `{\\color{green} ${P}}`, preview: '{\\color{green} x}' },
      { label: '加框强调', latex: `\\boxed{${P}}`, preview: '\\boxed{x=1}' },
      { label: '上标注释', latex: `\\overset{${P}}{${P}}`, preview: '\\overset{\\text{注}}{=}' },
      { label: '下标注释', latex: `\\underset{${P}}{${P}}`, preview: '\\underset{\\text{注}}{=}' },
      { label: '小号上标', latex: 'x^{\\scriptstyle n}' },
      { label: '下标前置（左侧上下标）', latex: `{}_{${P}}^{${P}}\\mathrm{X}`, preview: '{}_{6}^{12}\\mathrm{C}' },
    ],
  },
  {
    key: 'units',
    title: '单位与量纲',
    items: [
      { label: '米', latex: '\\mathrm{m}' },
      { label: '厘米', latex: '\\mathrm{cm}' },
      { label: '毫米', latex: '\\mathrm{mm}' },
      { label: '千米', latex: '\\mathrm{km}' },
      { label: '微米', latex: '\\mathrm{\\mu m}' },
      { label: '纳米', latex: '\\mathrm{nm}' },
      { label: '秒', latex: '\\mathrm{s}' },
      { label: '分钟', latex: '\\mathrm{min}' },
      { label: '小时', latex: '\\mathrm{h}' },
      { label: '克', latex: '\\mathrm{g}' },
      { label: '千克', latex: '\\mathrm{kg}' },
      { label: '吨', latex: '\\mathrm{t}' },
      { label: '摄氏度', latex: '\\mathrm{^\\circ C}' },
      { label: '开尔文', latex: '\\mathrm{K}' },
      { label: '摩尔', latex: '\\mathrm{mol}' },
      { label: '升', latex: '\\mathrm{L}' },
      { label: '毫升', latex: '\\mathrm{mL}' },
      { label: '速度（米每秒）', latex: '\\mathrm{m/s}' },
      { label: '速度（千米每时）', latex: '\\mathrm{km/h}' },
      { label: '加速度', latex: '\\mathrm{m/s^{2}}' },
      { label: '摩尔浓度', latex: '\\mathrm{mol/L}' },
      { label: '牛顿', latex: '\\mathrm{N}' },
      { label: '焦耳', latex: '\\mathrm{J}' },
      { label: '瓦特', latex: '\\mathrm{W}' },
      { label: '帕斯卡', latex: '\\mathrm{Pa}' },
      { label: '千帕', latex: '\\mathrm{kPa}' },
      { label: '赫兹', latex: '\\mathrm{Hz}' },
      { label: '伏特', latex: '\\mathrm{V}' },
      { label: '安培', latex: '\\mathrm{A}' },
      { label: '欧姆', latex: '\\mathrm{\\Omega}' },
      { label: '千欧', latex: '\\mathrm{k\\Omega}' },
      { label: '法拉', latex: '\\mathrm{F}' },
      { label: '微法', latex: '\\mathrm{\\mu F}' },
      { label: '亨利', latex: '\\mathrm{H}' },
      { label: '特斯拉', latex: '\\mathrm{T}' },
      { label: '库仑', latex: '\\mathrm{C}' },
      { label: '电子伏特', latex: '\\mathrm{eV}' },
      { label: '焦每摩', latex: '\\mathrm{kJ \\cdot mol^{-1}}' },
      { label: '千瓦时', latex: '\\mathrm{kW \\cdot h}' },
      { label: '数量级模板', latex: `10^{${P}}`, preview: '10^{8}' },
      { label: '科学计数法模板', latex: `${P} \\times 10^{${P}}`, preview: '6.02 \\times 10^{23}' },
      { label: '相对误差', latex: '\\frac{\\Delta x}{x} \\times 100\\%' },
    ],
  },
  {
    key: 'physics',
    title: '物理',
    items: [
      { label: '匀变速速度公式', latex: 'v = v_{0} + at' },
      { label: '匀变速位移公式', latex: 'x = v_{0}t + \\frac{1}{2}at^{2}' },
      { label: '速度位移关系', latex: 'v^{2} - v_{0}^{2} = 2ax' },
      { label: '平均速度', latex: '\\bar{v} = \\frac{x}{t}' },
      { label: '牛顿第二定律', latex: '\\vec{F} = m\\vec{a}' },
      { label: '重力', latex: 'G = mg' },
      { label: '摩擦力', latex: 'f = \\mu N' },
      { label: '胡克定律', latex: 'F = kx' },
      { label: '万有引力定律', latex: 'F = G\\frac{m_{1}m_{2}}{r^{2}}' },
      { label: '圆周运动加速度', latex: 'a = \\frac{v^{2}}{r} = \\omega^{2}r' },
      { label: '向心力', latex: 'F = m\\frac{v^{2}}{r}' },
      { label: '线速度与角速度', latex: 'v = \\omega r = \\frac{2\\pi r}{T}' },
      { label: '平抛运动竖直位移', latex: 'y = \\frac{1}{2}gt^{2}' },
      { label: '功', latex: 'W = Fl\\cos\\theta' },
      { label: '功率', latex: 'P = \\frac{W}{t} = Fv' },
      { label: '动能', latex: 'E_{\\mathrm{k}} = \\frac{1}{2}mv^{2}' },
      { label: '重力势能', latex: 'E_{\\mathrm{p}} = mgh' },
      { label: '动能定理', latex: 'W_{\\text{合}} = \\Delta E_{\\mathrm{k}}' },
      { label: '机械能守恒', latex: 'E_{\\mathrm{k}1} + E_{\\mathrm{p}1} = E_{\\mathrm{k}2} + E_{\\mathrm{p}2}' },
      { label: '动量', latex: 'p = mv' },
      { label: '动量定理', latex: 'Ft = \\Delta p = mv_{2} - mv_{1}' },
      { label: '动量守恒', latex: 'm_{1}v_{1} + m_{2}v_{2} = m_{1}v_{1}\\prime + m_{2}v_{2}\\prime' },
      { label: '简谐运动方程', latex: 'x = A\\sin(\\omega t + \\varphi)' },
      { label: '单摆周期', latex: 'T = 2\\pi\\sqrt{\\frac{L}{g}}' },
      { label: '欧姆定律', latex: 'I = \\frac{U}{R}' },
      { label: '电阻定律', latex: 'R = \\rho\\frac{L}{S}' },
      { label: '电功率', latex: 'P = UI = I^{2}R = \\frac{U^{2}}{R}' },
      { label: '电功', latex: 'W = UIt' },
      { label: '焦耳定律', latex: 'Q = I^{2}Rt' },
      { label: '闭合电路欧姆定律', latex: '\\varepsilon = I(R + r)' },
      { label: '电容', latex: 'C = \\frac{Q}{U}' },
      { label: '电场强度', latex: 'E = \\frac{F}{q}' },
      { label: '匀强电场', latex: 'E = \\frac{U}{d}' },
      { label: '库仑定律', latex: 'F = k\\frac{q_{1}q_{2}}{r^{2}}' },
      { label: '电势能', latex: 'E_{\\mathrm{p}} = q\\varphi' },
      { label: '电场力做功', latex: 'W = qU' },
      { label: '电流微观表达式', latex: 'I = nqvS' },
      { label: '磁通量', latex: '\\Phi = BS\\cos\\theta' },
      { label: '安培力', latex: 'F = BIL\\sin\\theta' },
      { label: '洛伦兹力', latex: 'f = qvB' },
      { label: '带电粒子圆周半径', latex: 'r = \\frac{mv}{qB}' },
      { label: '带电粒子周期', latex: 'T = \\frac{2\\pi m}{qB}' },
      { label: '法拉第电磁感应定律', latex: '\\varepsilon = n\\frac{\\Delta\\Phi}{\\Delta t}' },
      { label: '动生电动势', latex: '\\varepsilon = BLv' },
      { label: '楞次定律（负号）', latex: '\\varepsilon = -\\frac{\\Delta\\Phi}{\\Delta t}' },
      { label: '自感电动势', latex: '\\varepsilon = L\\frac{\\Delta I}{\\Delta t}' },
      { label: '理想变压器', latex: '\\frac{U_{1}}{U_{2}} = \\frac{n_{1}}{n_{2}}' },
      { label: '交变电流瞬时值', latex: 'e = E_{\\mathrm{m}}\\sin\\omega t' },
      { label: '交流有效值', latex: 'U = \\frac{U_{\\mathrm{m}}}{\\sqrt{2}}' },
      { label: '波速公式', latex: 'v = \\lambda f = \\frac{\\lambda}{T}' },
      { label: '折射定律', latex: 'n = \\frac{\\sin\\theta_{1}}{\\sin\\theta_{2}} = \\frac{c}{v}' },
      { label: '全反射临界角', latex: '\\sin C = \\frac{1}{n}' },
      { label: '透镜成像公式', latex: '\\frac{1}{u} + \\frac{1}{v} = \\frac{1}{f}' },
      { label: '双缝干涉条纹间距', latex: '\\Delta y = \\frac{L}{d}\\lambda' },
      { label: '光子能量', latex: 'E = h\\nu' },
      { label: '光电效应方程', latex: 'E_{\\mathrm{k}} = h\\nu - W_{0}' },
      { label: '德布罗意波长', latex: '\\lambda = \\frac{h}{p}' },
      { label: '热力学第一定律', latex: '\\Delta U = Q + W' },
      { label: '热平衡方程', latex: 'Q_{\\text{吸}} = Q_{\\text{放}}' },
      { label: '吸热公式', latex: 'Q = cm\\Delta t' },
      { label: '理想气体状态方程', latex: 'pV = nRT' },
      { label: '气体实验定律（三态）', latex: '\\frac{p_{1}V_{1}}{T_{1}} = \\frac{p_{2}V_{2}}{T_{2}}' },
      { label: '分子平均动能', latex: '\\bar{E}_{\\mathrm{k}} = \\frac{3}{2}kT' },
      { label: '质能方程', latex: 'E = mc^{2}' },
      { label: '质能亏损', latex: '\\Delta E = \\Delta m c^{2}' },
      { label: 'α 衰变方程', latex: '\\ce{^{238}_{92}U -> ^{234}_{90}Th + ^{4}_{2}He}' },
      { label: 'β 衰变方程', latex: '\\ce{^{234}_{90}Th -> ^{234}_{91}Pa + ^{0}_{-1}e}' },
      { label: '重力加速度常量', latex: 'g = 9.8\\,\\mathrm{m/s^{2}}' },
      { label: '光速常量', latex: 'c = 3 \\times 10^{8}\\,\\mathrm{m/s}' },
      { label: '静电力常量', latex: 'k = 9.0 \\times 10^{9}\\,\\mathrm{N \\cdot m^{2}/C^{2}}' },
      { label: '普朗克常量', latex: 'h = 6.63 \\times 10^{-34}\\,\\mathrm{J \\cdot s}' },
      { label: '元电荷', latex: 'e = 1.6 \\times 10^{-19}\\,\\mathrm{C}' },
      { label: '阿伏加德罗常量', latex: 'N_{\\mathrm{A}} = 6.02 \\times 10^{23}\\,\\mathrm{mol^{-1}}' },
      { label: '真空介电常量', latex: '\\varepsilon_{0}' },
      { label: '真空磁导率', latex: '\\mu_{0}' },
      { label: '磁通量变化率', latex: '\\frac{\\Delta\\Phi}{\\Delta t}' },
      { label: '电场线与磁感线强度', latex: 'B = \\frac{F}{IL}' },
      { label: '电阻串联', latex: 'R = R_{1} + R_{2} + \\cdots + R_{n}' },
      { label: '电阻并联', latex: '\\frac{1}{R} = \\frac{1}{R_{1}} + \\frac{1}{R_{2}}' },
      { label: '半衰期', latex: 'N = N_{0}\\left( \\frac{1}{2} \\right)^{\\frac{t}{T}}' },
    ],
  },
  {
    key: 'chemistry',
    title: '化学',
    items: [
      { label: '化学式：水', latex: '\\ce{H2O}' },
      { label: '化学式：二氧化碳', latex: '\\ce{CO2}' },
      { label: '化学式：氢氧化钙', latex: '\\ce{Ca(OH)2}' },
      { label: '化学式：硫酸铝', latex: '\\ce{Al2(SO4)3}' },
      { label: '化学式：硫酸铜晶体', latex: '\\ce{CuSO4.5H2O}' },
      { label: '化学式：碳酸钙', latex: '\\ce{CaCO3}' },
      { label: '化学式：高锰酸钾', latex: '\\ce{KMnO4}' },
      { label: '化学式：碳酸氢钠', latex: '\\ce{NaHCO3}' },
      { label: '化学式模板', latex: `\\ce{${P}}`, preview: '\\ce{Fe2O3}' },
      { label: '离子：钠离子', latex: '\\ce{Na+}' },
      { label: '离子：氯离子', latex: '\\ce{Cl-}' },
      { label: '离子：氢氧根', latex: '\\ce{OH-}' },
      { label: '离子：硫酸根', latex: '\\ce{SO4^2-}' },
      { label: '离子：碳酸根', latex: '\\ce{CO3^2-}' },
      { label: '离子：铵根', latex: '\\ce{NH4+}' },
      { label: '离子：铁离子', latex: '\\ce{Fe^3+}' },
      { label: '离子：铜离子', latex: '\\ce{Cu^2+}' },
      { label: '离子：锰酸根', latex: '\\ce{MnO4-}' },
      { label: '离子：水合氢离子', latex: '\\ce{H3O+}' },
      { label: '离子模板', latex: `\\ce{${P}^${P}${P}}`, preview: '\\ce{Fe^2+}' },
      { label: '反应箭头', latex: '\\ce{->}' },
      { label: '可逆反应箭头', latex: '\\ce{<=>}' },
      { label: '长期可逆箭头', latex: '\\ce{<=>>}' },
      { label: '加热条件（Δ）', latex: '\\ce{->[\\Delta]}' },
      { label: '点燃条件', latex: '\\ce{->[\\text{点燃}]}' },
      { label: '催化剂条件', latex: '\\ce{->[\\text{催化剂}]}' },
      { label: '高温条件', latex: '\\ce{->[\\text{高温}]}' },
      { label: '光照条件', latex: '\\ce{->[\\text{光照}]}' },
      { label: '通电条件', latex: '\\ce{->[\\text{通电}]}' },
      { label: '上下双条件箭头', latex: '\\ce{->[\\text{高温}][\\text{催化剂}]}' },
      { label: '沉淀符号（↓）', latex: '\\ce{CaCO3 v}' },
      { label: '气体符号（↑）', latex: '\\ce{H2 ^}' },
      { label: '气体符号（附于反应）', latex: '\\ce{Zn + H2SO4 -> ZnSO4 + H2 ^}' },
      { label: '水的中文状态标注', latex: '\\ce{2H2(g) + O2(g) -> 2H2O(l)}' },
      { label: '燃烧反应：甲烷', latex: '\\ce{CH4 + 2O2 ->[\\text{点燃}] CO2 + 2H2O}' },
      { label: '分解反应：过氧化氢', latex: '\\ce{2H2O2 ->[\\ce{MnO2}] 2H2O + O2 ^}' },
      { label: '置换反应：铁与硫酸铜', latex: '\\ce{Fe + CuSO4 -> FeSO4 + Cu}' },
      { label: '中和反应', latex: '\\ce{NaOH + HCl -> NaCl + H2O}' },
      { label: '高温分解：碳酸钙', latex: '\\ce{CaCO3 ->[\\text{高温}] CaO + CO2 ^}' },
      { label: '铝热反应', latex: '\\ce{2Al + Fe2O3 ->[\\text{高温}] Al2O3 + 2Fe}' },
      { label: '合成氨（可逆）', latex: '\\ce{N2 + 3H2 <=>[\\text{高温高压}][\\text{催化剂}] 2NH3}' },
      { label: '钠与水反应', latex: '\\ce{2Na + 2H2O -> 2NaOH + H2 ^}' },
      { label: '离子方程式：中和', latex: '\\ce{H+ + OH- -> H2O}' },
      { label: '离子方程式：沉淀', latex: '\\ce{Ca^2+ + CO3^2- -> CaCO3 v}' },
      { label: '离子方程式：铁与酸', latex: '\\ce{Fe + 2H+ -> Fe^2+ + H2 ^}' },
      { label: '离子方程式：氯气与碱', latex: '\\ce{Cl2 + 2OH- -> Cl- + ClO- + H2O}' },
      { label: '电离方程式：强电解质', latex: '\\ce{NaCl -> Na+ + Cl-}' },
      { label: '电离方程式：弱电解质', latex: '\\ce{CH3COOH <=> H+ + CH3COO-}' },
      { label: '水解方程式', latex: '\\ce{CO3^2- + H2O <=> HCO3- + OH-}' },
      { label: '原电池负极反应', latex: '\\ce{Zn - 2e- -> Zn^2+}' },
      { label: '原电池正极反应', latex: '\\ce{Cu^2+ + 2e- -> Cu}' },
      { label: '电解池阳极反应', latex: '\\ce{2Cl- - 2e- -> Cl2 ^}' },
      { label: '电解池阴极反应', latex: '\\ce{2H2O + 2e- -> H2 ^ + 2OH-}' },
      { label: '热化学方程式', latex: '\\ce{C(s) + O2(g) -> CO2(g)} \\quad \\Delta H = -393.5\\,\\mathrm{kJ \\cdot mol^{-1}}' },
      { label: '中和热', latex: '\\ce{H+(aq) + OH-(aq) -> H2O(l)} \\quad \\Delta H = -57.3\\,\\mathrm{kJ \\cdot mol^{-1}}' },
      { label: '化学平衡常数', latex: 'K_{c} = \\frac{[\\ce{C}]^{c}[\\ce{D}]^{d}}{[\\ce{A}]^{a}[\\ce{B}]^{b}}' },
      { label: '溶度积常数', latex: 'K_{\\mathrm{sp}}(\\ce{AgCl}) = c(\\ce{Ag+}) \\cdot c(\\ce{Cl-})' },
      { label: '水的离子积', latex: 'K_{\\mathrm{w}} = c(\\ce{H+}) \\cdot c(\\ce{OH-}) = 1 \\times 10^{-14}' },
      { label: '反应速率方程', latex: 'v = k c^{a}(\\ce{A}) c^{b}(\\ce{B})' },
      { label: '勒夏特列（放热）', latex: '\\ce{N2 + 3H2 <=> 2NH3} \\quad \\Delta H \\lt 0' },
      { label: '物质的量', latex: 'n = \\frac{m}{M}' },
      { label: '物质的量浓度', latex: 'c = \\frac{n}{V}' },
      { label: '气体摩尔体积', latex: 'V = n \\cdot V_{\\mathrm{m}}' },
      { label: '微粒数', latex: 'N = n \\cdot N_{\\mathrm{A}}' },
      { label: '溶液稀释', latex: 'c_{1}V_{1} = c_{2}V_{2}' },
      { label: '溶质质量分数', latex: 'w = \\frac{m_{\\text{质}}}{m_{\\text{液}}} \\times 100\\%' },
      { label: 'pH 计算', latex: '\\mathrm{pH} = -\\lg c(\\ce{H+})' },
      { label: 'pH 与 pOH', latex: '\\mathrm{pH} + \\mathrm{pOH} = 14' },
      { label: '电子排布式', latex: '1s^{2}2s^{2}2p^{6}3s^{2}3p^{6}3d^{10}4s^{1}' },
      { label: '电子排布（简化）', latex: '[\\mathrm{Ar}]3d^{10}4s^{1}' },
      { label: '同位素标记', latex: '\\ce{^{235}_{92}U}' },
      { label: '络离子', latex: '\\ce{[Cu(NH3)4]^2+}' },
      { label: '官能团：羟基', latex: '\\ce{-OH}' },
      { label: '官能团：羧基', latex: '\\ce{-COOH}' },
      { label: '官能团：醛基', latex: '\\ce{-CHO}' },
      { label: '官能团：氨基', latex: '\\ce{-NH2}' },
      { label: '官能团：硝基', latex: '\\ce{-NO2}' },
      { label: '有机物：乙醇', latex: '\\ce{CH3CH2OH}' },
      { label: '有机物：乙酸', latex: '\\ce{CH3COOH}' },
      { label: '有机物：乙烯', latex: '\\ce{CH2=CH2}' },
      { label: '有机物：苯', latex: '\\ce{C6H6}' },
      { label: '有机物：葡萄糖', latex: '\\ce{C6H12O6}' },
      { label: '乙醇催化氧化', latex: '\\ce{2CH3CH2OH + O2 ->[\\ce{Cu}][\\Delta] 2CH3CHO + 2H2O}' },
      { label: '酯化反应', latex: '\\ce{CH3COOH + C2H5OH <=>[\\text{浓硫酸}][\\Delta] CH3COOC2H5 + H2O}' },
      { label: '加成反应：乙烯与溴', latex: '\\ce{CH2=CH2 + Br2 -> CH2BrCH2Br}' },
      { label: '结构简式模板', latex: `\\ce{${P}}`, preview: '\\ce{CH3CH2CH3}' },
    ],
  },
  {
    key: 'biology',
    title: '生物',
    items: [
      { label: '杂交符号', latex: '\\times' },
      { label: '自交符号', latex: '\\otimes' },
      { label: '母本（雌性）', latex: '\\text{♀}' },
      { label: '父本（雄性）', latex: '\\text{♂}' },
      { label: '亲本 P', latex: '\\mathrm{P}' },
      { label: '子一代 F1', latex: '\\mathrm{F}_{1}' },
      { label: '子二代 F2', latex: '\\mathrm{F}_{2}' },
      { label: '杂交组合', latex: '\\mathrm{P}: \\mathrm{AA} \\times \\mathrm{aa} \\to \\mathrm{F}_{1}' },
      { label: '基因型：杂合子', latex: '\\mathrm{Aa}' },
      { label: '基因型：纯合子', latex: '\\mathrm{AA}' },
      { label: '基因型：两对基因', latex: '\\mathrm{AaBb}' },
      { label: '基因型：伴性遗传', latex: '\\mathrm{X}^{\\mathrm{B}}\\mathrm{X}^{\\mathrm{b}}' },
      { label: '基因型：男性伴性', latex: '\\mathrm{X}^{\\mathrm{B}}\\mathrm{Y}' },
      { label: '测交', latex: '\\mathrm{Aa} \\times \\mathrm{aa} \\to 1:1' },
      { label: '自交后代比例', latex: '\\mathrm{Aa} \\times \\mathrm{Aa} \\to 3:1' },
      { label: '自由组合比例', latex: '9:3:3:1' },
      { label: '遗传图解表格', latex: `\\begin{array}{c|c|c} & ${P} & ${P} \\\\ \\hline ${P} & ${P} & ${P} \\\\ \\hline ${P} & ${P} & ${P} \\end{array}`, preview: '\\begin{array}{c|c|c} & \\mathrm{A} & \\mathrm{a} \\\\ \\hline \\mathrm{A} & \\mathrm{AA} & \\mathrm{Aa} \\\\ \\hline \\mathrm{a} & \\mathrm{Aa} & \\mathrm{aa} \\end{array}' },
      { label: '杂合子概率', latex: '\\frac{1}{2}' },
      { label: '基因频率', latex: 'p + q = 1' },
      { label: '哈迪-温伯格定律', latex: 'p^{2} + 2pq + q^{2} = 1' },
      { label: '碱基互补配对', latex: '\\mathrm{A} = \\mathrm{T}, \\quad \\mathrm{G} \\equiv \\mathrm{C}' },
      { label: '碱基比例', latex: '\\frac{\\mathrm{A} + \\mathrm{T}}{\\mathrm{G} + \\mathrm{C}}' },
      { label: '密码子', latex: '\\mathrm{AUG}' },
      { label: '染色体数（二倍体）', latex: '2n = 4' },
      { label: '配子染色体数', latex: 'n = 2' },
      { label: '细胞周期', latex: '\\mathrm{G}_{1} \\to \\mathrm{S} \\to \\mathrm{G}_{2} \\to \\mathrm{M}' },
      { label: '有氧呼吸总反应', latex: '\\ce{C6H12O6 + 6O2 ->[\\text{酶}] 6CO2 + 6H2O + \\text{能量}}' },
      { label: '无氧呼吸（酒精发酵）', latex: '\\ce{C6H12O6 ->[\\text{酶}] 2C2H5OH + 2CO2 + \\text{少量能量}}' },
      { label: '光合作用总反应', latex: '\\ce{6CO2 + 6H2O ->[\\text{光能}][\\text{叶绿体}] C6H12O6 + 6O2}' },
      { label: '水的光解', latex: '\\ce{2H2O ->[\\text{光}][\\text{叶绿体}] 4H+ + O2 + 4e-}' },
      { label: 'ATP 与 ADP 转化', latex: '\\ce{ATP <=>[\\text{酶}] ADP + Pi + \\text{能量}}' },
      { label: '渗透压公式', latex: '\\pi = cRT' },
      { label: '米氏方程', latex: 'v = \\frac{V_{\\mathrm{max}}[S]}{K_{\\mathrm{m}} + [S]}' },
      { label: '血液 pH 范围', latex: '\\mathrm{pH} = 7.35 \\sim 7.45' },
      { label: '血糖正常范围', latex: '3.9 \\sim 6.1\\,\\mathrm{mmol/L}' },
      { label: '种群增长模型', latex: 'N_{t} = N_{0}\\lambda^{t}' },
      { label: '逻辑斯谛增长模型', latex: '\\frac{dN}{dt} = rN\\left( 1 - \\frac{N}{K} \\right)' },
      { label: '标志重捕法', latex: '\\frac{N}{M} = \\frac{n}{m}' },
      { label: '能量传递效率', latex: '10\\% \\sim 20\\%' },
      { label: 'DNA 复制半保留', latex: '\\text{亲代} \\to 2\\,\\text{个子代 DNA}' },
    ],
  },
]
